name: flower_app
description: Flower e-commerce app — Flutter + Firebase (Auth, Firestore, Storage) with Provider state management.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  email_validator: '^2.1.16'
  flutter_pw_validator: ^1.6.0
  google_sign_in: ^6.1.4
  font_awesome_flutter: ^10.5.0
  cloud_firestore: ^4.8.4
  intl: ^0.18.1
  firebase_storage: ^11.2.5
  image_picker: ^1.0.1

  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  image_path_android: "assets/icons/logo.png"
  image_path_ios: "assets/icons/logo.png"
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/logo.png"
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
